-- 000_legacy_pre_migration_baseline.sql
--
-- WHY THIS EXISTS
-- ---------------
-- Seven tables and two enum types in production pre-date this project's
-- migration system entirely. No migration in 001..066 creates them, yet
-- migration 004 (`004_lock_legacy_tables.sql`) locks them down with RLS.
--
-- The practical consequence, confirmed 2026-09-08: the migration chain could
-- never be replayed from scratch on a fresh database -- it died at 004 on
-- tables that nothing had created. That is a large part of why a Supabase
-- development branch reported MIGRATIONS_FAILED, and why no migration in this
-- repository has ever been validated before being applied to production.
--
-- This baseline restores replayability by declaring the pre-migration objects
-- exactly as they exist in production today (shapes read directly from
-- information_schema / pg_enum on 2026-09-08).
--
-- SAFETY
-- ------
-- Every statement is IF NOT EXISTS / guarded. Applying this to a database that
-- already has these objects (i.e. production) is a no-op. It is intended to
-- run only on fresh databases -- CI, local dev, and preview branches.
--
-- These tables are dormant legacy carry-over. Nothing in the current
-- application reads or writes them; migration 004 exists specifically to keep
-- them locked down.

-- Legacy enum types (created outside the migration system, like the tables below).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                 WHERE t.typname = 'jobstatus' AND n.nspname = 'public') THEN
    CREATE TYPE public.jobstatus AS ENUM ('pending', 'running', 'done', 'failed');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                 WHERE t.typname = 'plantier' AND n.nspname = 'public') THEN
    CREATE TYPE public.plantier AS ENUM ('free', 'starter', 'growth', 'pro', 'agency');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY,
  email character varying NOT NULL,
  password_hash character varying NOT NULL,
  full_name character varying,
  plan public.plantier NOT NULL,
  is_active boolean NOT NULL,
  is_verified boolean NOT NULL,
  created_at timestamp without time zone NOT NULL,
  subscription_expires_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.seller_credentials (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL,
  marketplace character varying NOT NULL,
  seller_id character varying,
  sp_refresh_token_enc text,
  ads_refresh_token_enc text,
  ads_profile_id character varying,
  connected_at timestamp without time zone NOT NULL,
  last_sync_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.asins (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL,
  asin character varying NOT NULL,
  marketplace character varying NOT NULL,
  label character varying,
  is_active boolean NOT NULL,
  created_at timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bsr_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asin_id uuid NOT NULL,
  bsr_rank integer,
  category character varying,
  sub_rank integer,
  sub_category character varying,
  captured_at timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.job_logs (
  id uuid PRIMARY KEY,
  user_id uuid,
  job_type character varying NOT NULL,
  status public.jobstatus NOT NULL,
  error_message text,
  started_at timestamp without time zone NOT NULL,
  completed_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.keyword_ranks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  asin character varying NOT NULL,
  keyword character varying NOT NULL,
  rank integer,
  page integer,
  marketplace character varying NOT NULL,
  captured_at timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tool_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  tool character varying NOT NULL,
  input_count integer NOT NULL,
  result_count integer,
  marketplace character varying,
  task_id character varying,
  created_at timestamp without time zone NOT NULL
);
