import { Asin, BsrSummary, Insight, ProductSnapshot } from '@/types'

export const MOCK_ASINS: Asin[] = [
  {
    id: '1',
    user_id: 'mock-user',
    asin: 'B0BN5NZCGH',
    label: 'Daily Herbs Ghee 1L',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: '2',
    user_id: 'mock-user',
    asin: 'B09W2N5K3X',
    label: 'Herbal Tea Blend 250g',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: '3',
    user_id: 'mock-user',
    asin: 'B07XQFM2XK',
    label: 'Organic Turmeric Powder',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: '4',
    user_id: 'mock-user',
    asin: 'B0C3KJR45M',
    label: 'Neem Face Wash 200ml',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: '5',
    user_id: 'mock-user',
    asin: 'B08JK2MN7P',
    label: 'Ashwagandha Capsules 60ct',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
]

export const MOCK_BSR_SUMMARY: BsrSummary[] = [
  {
    asin_id: '1',
    asin: 'B0BN5NZCGH',
    label: 'Daily Herbs Ghee 1L',
    marketplace: 'IN',
    bsr_rank: 342,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 12,
    sub_category: 'Ghee',
    captured_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    asin_id: '2',
    asin: 'B09W2N5K3X',
    label: 'Herbal Tea Blend 250g',
    marketplace: 'IN',
    bsr_rank: 1842,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 45,
    sub_category: 'Herbal Tea',
    captured_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    asin_id: '3',
    asin: 'B07XQFM2XK',
    label: 'Organic Turmeric Powder',
    marketplace: 'IN',
    bsr_rank: 5621,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 89,
    sub_category: 'Spices',
    captured_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    asin_id: '4',
    asin: 'B0C3KJR45M',
    label: 'Neem Face Wash 200ml',
    marketplace: 'IN',
    bsr_rank: 289,
    category: 'Beauty & Personal Care',
    sub_rank: 8,
    sub_category: 'Face Wash',
    captured_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    asin_id: '5',
    asin: 'B08JK2MN7P',
    label: 'Ashwagandha Capsules 60ct',
    marketplace: 'IN',
    bsr_rank: null,
    category: null,
    sub_rank: null,
    sub_category: null,
    captured_at: null,
  },
]

export function generateMockHistory(asin_id: string, days = 30) {
  const now = Date.now()
  const baseline: Record<string, number> = {
    '1': 350,
    '2': 1800,
    '3': 5500,
    '4': 300,
    '5': 2000,
  }
  const base = baseline[asin_id] ?? 1000
  return Array.from({ length: days }, (_, i) => ({
    captured_at: new Date(now - (days - i) * 24 * 60 * 60 * 1000).toISOString(),
    bsr_rank: Math.max(1, base + Math.round((Math.random() - 0.5) * base * 0.2)),
  }))
}

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: '1',
    type: 'bsr_change',
    title: 'BSR Improved',
    description: 'Daily Herbs Ghee 1L moved from #380 → #342 in Grocery',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    severity: 'success',
  },
  {
    id: '2',
    type: 'scrape_complete',
    title: 'Scrape Complete',
    description: 'Refreshed BSR for 4/5 ASINs successfully',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    severity: 'info',
  },
  {
    id: '3',
    type: 'alert',
    title: 'Rank Drop Alert',
    description: 'Herbal Tea Blend dropped 200+ positions',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    severity: 'warning',
  },
  {
    id: '4',
    type: 'new_asin',
    title: 'ASIN Added',
    description: 'Ashwagandha Capsules is now being tracked',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    severity: 'info',
  },
]

export const MOCK_PRODUCT_SNAPSHOTS: ProductSnapshot[] = [
  {
    id: '1',
    asin: 'B0BN5NZCGH',
    label: 'Daily Herbs Ghee 1L',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    bsr_rank: 342,
    bsr_rank_prev: 380,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 12,
    sub_category: 'Ghee',
    price: 1299,
    price_currency: 'INR',
    rating: 4.3,
    review_count: 1240,
    buybox_winner: 'Daily Herbs Official',
    buybox_is_self: true,
    availability: 'in_stock',
    availability_score: 95,
    captured_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: '2',
    asin: 'B09W2N5K3X',
    label: 'Herbal Tea Blend 250g',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    bsr_rank: 1842,
    bsr_rank_prev: 1650,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 45,
    sub_category: 'Herbal Tea',
    price: 549,
    price_currency: 'INR',
    rating: 4.1,
    review_count: 387,
    buybox_winner: 'TeaWorld Store',
    buybox_is_self: false,
    availability: 'in_stock',
    availability_score: 82,
    captured_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: '3',
    asin: 'B07XQFM2XK',
    label: 'Organic Turmeric Powder',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    bsr_rank: 5621,
    bsr_rank_prev: 4900,
    category: 'Grocery & Gourmet Foods',
    sub_rank: 89,
    sub_category: 'Spices',
    price: 299,
    price_currency: 'INR',
    rating: 3.8,
    review_count: 912,
    buybox_winner: null,
    buybox_is_self: null,
    availability: 'limited',
    availability_score: 35,
    captured_at: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: '4',
    asin: 'B0C3KJR45M',
    label: 'Neem Face Wash 200ml',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    bsr_rank: 289,
    bsr_rank_prev: 315,
    category: 'Beauty & Personal Care',
    sub_rank: 8,
    sub_category: 'Face Wash',
    price: 349,
    price_currency: 'INR',
    rating: 4.5,
    review_count: 2840,
    buybox_winner: 'NaturaBeauty Co.',
    buybox_is_self: false,
    availability: 'in_stock',
    availability_score: 98,
    captured_at: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: '5',
    asin: 'B08JK2MN7P',
    label: 'Ashwagandha Capsules 60ct',
    marketplace: 'IN',
    is_active: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    bsr_rank: null,
    bsr_rank_prev: null,
    category: null,
    sub_rank: null,
    sub_category: null,
    price: null,
    price_currency: 'INR',
    rating: null,
    review_count: null,
    buybox_winner: null,
    buybox_is_self: null,
    availability: null,
    availability_score: null,
    captured_at: null,
  },
]
