#!/usr/bin/env python3
"""
YouTube Shorts Video Creator — AI-powered video production from scripts.

Takes the scripts generated by youtube_viral_titles.py (Step 6) and turns
each one into a ready-to-upload vertical video (1080×1920) with:
  - AI voiceover (ElevenLabs or free Edge-TTS)
  - AI-generated scene images (Gemini) or styled text slides
  - Automatic assembly with transitions and subtitles

Requirements:
  pip install edge-tts Pillow moviepy
  # Optional for better quality:
  pip install elevenlabs google-genai

  For AI image generation (optional):
    GEMINI_API_KEY env var

  For premium voiceover (optional):
    ELEVENLABS_API_KEY env var

Usage:
  # Create videos from scripts file
  python create_shorts.py --scripts calmcreations15_results/scripts.md

  # Use ElevenLabs voice (premium quality)
  python create_shorts.py --scripts scripts.md --voice elevenlabs

  # Generate AI images for scenes
  python create_shorts.py --scripts scripts.md --ai-images

  # Create only the first N videos
  python create_shorts.py --scripts scripts.md --limit 3

  # Custom output directory
  python create_shorts.py --scripts scripts.md --output-dir ./my_videos
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys
import textwrap
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Script parser — extract structured scenes from markdown scripts
# ---------------------------------------------------------------------------

def parse_scripts(scripts_text: str) -> list[dict]:
    """
    Parse the markdown scripts file into structured video data.

    Expected format per script block (separated by ---):
        ## N. Title
        **Hook (0-3 sec):** ...
        **Visual:** ...
        **Body (3-45 sec):** ...
        **Visual Sequence:** ...
        **Climax/Reveal (45-55 sec):** ...
        **Visual:** ...
        **CTA (55-60 sec):** ...
    """
    videos = []

    # Split by --- separators
    script_blocks = re.split(r"\n---\n", scripts_text)

    for block in script_blocks:
        block = block.strip()
        if not block:
            continue

        # Extract title
        title_match = re.search(r"##\s*\d*\.?\s*(.+)", block)
        if not title_match:
            continue
        title = title_match.group(1).strip()

        # Split block into labelled sections by **Label:** pattern
        # Each section: (label, content)
        sections: list[tuple[str, str]] = []
        parts = re.split(r"\*\*(.+?)\*\*:?\s*", block)
        # parts = [preamble, label1, content1, label2, content2, ...]
        for i in range(1, len(parts) - 1, 2):
            label = parts[i].strip().lower()
            content = parts[i + 1].strip()
            sections.append((label, content))

        # Helper to find section by keyword
        def _find(keyword: str) -> str:
            for lbl, txt in sections:
                if keyword in lbl:
                    return txt
            return ""

        hook_vo = _find("hook")
        hook_visual = _find("visual")  # first "visual" after hook
        body_vo = _find("body")
        climax_vo = _find("climax")
        cta_vo = _find("cta")

        # Find visual sequence specifically
        body_visual = ""
        climax_visual = ""
        for lbl, txt in sections:
            if "visual sequence" in lbl:
                body_visual = txt
            elif "visual" in lbl and climax_vo and sections.index((lbl, txt)) > next(
                (i for i, (l, _) in enumerate(sections) if "climax" in l), 999
            ):
                climax_visual = txt

        # Build scene list
        scenes = []

        # Scene 1: Hook
        if hook_vo:
            scenes.append({
                "type": "hook",
                "voiceover": _clean_vo(hook_vo),
                "visual_desc": hook_visual or "Dramatic opening shot",
                "duration_hint": 3,
            })

        # Scene 2-4: Body (split into sub-scenes)
        if body_vo:
            body_sentences = _split_into_sentences(body_vo)
            body_visuals = (body_visual or "").split("→")
            for i, sentence in enumerate(body_sentences):
                sentence = _clean_vo(sentence)
                if not sentence or len(sentence) < 10:
                    continue
                visual = body_visuals[i].strip() if i < len(body_visuals) else "Build montage"
                scenes.append({
                    "type": "body",
                    "voiceover": sentence,
                    "visual_desc": visual,
                    "duration_hint": 8,
                })

        # Scene 5: Climax
        if climax_vo:
            scenes.append({
                "type": "climax",
                "voiceover": _clean_vo(climax_vo),
                "visual_desc": climax_visual or "Big reveal shot",
                "duration_hint": 10,
            })

        # Scene 6: CTA
        if cta_vo:
            scenes.append({
                "type": "cta",
                "voiceover": _clean_vo(cta_vo),
                "visual_desc": "Text overlay with question",
                "duration_hint": 5,
            })

        if scenes:
            videos.append({
                "title": title,
                "scenes": scenes,
                "full_voiceover": " ".join(s["voiceover"] for s in scenes),
            })

    return videos


def _clean_vo(text: str) -> str:
    """Clean voiceover text — remove markdown, SFX tags for TTS."""
    text = re.sub(r"\[SFX:.*?\]", "", text)
    text = re.sub(r"\*\*.*?\*\*:?\s*", "", text)
    text = re.sub(r"\*", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _split_into_sentences(text: str) -> list[str]:
    """Split body text into logical sentences/chunks."""
    text = _clean_vo(text)
    # Split on periods, but keep the sentence together if short
    raw = re.split(r"(?<=[.!?])\s+", text)
    # Merge very short sentences
    merged = []
    buffer = ""
    for s in raw:
        buffer = (buffer + " " + s).strip() if buffer else s
        if len(buffer) > 40:
            merged.append(buffer)
            buffer = ""
    if buffer:
        merged.append(buffer)
    return merged if merged else [text]


# ---------------------------------------------------------------------------
# Voiceover generation
# ---------------------------------------------------------------------------

async def generate_voiceover_edge(text: str, output_path: Path, voice: str = "en-US-ChristopherNeural") -> Path:
    """Generate voiceover using Edge-TTS (free, no API key needed)."""
    import edge_tts

    for attempt in range(3):
        try:
            communicate = edge_tts.Communicate(text, voice, rate="+10%")
            await communicate.save(str(output_path))
            # Validate output
            if output_path.exists() and output_path.stat().st_size > 100:
                return output_path
            raise RuntimeError(f"Edge-TTS produced empty file ({output_path.stat().st_size if output_path.exists() else 'missing'} bytes)")
        except Exception as e:
            if attempt < 2:
                wait = 3 * (attempt + 1)
                print(f"        Edge-TTS attempt {attempt+1} failed: {e}, retrying in {wait}s...")
                await asyncio.sleep(wait)
            else:
                raise


async def generate_all_voiceovers_edge(
    texts: list[str], output_paths: list[Path], voice: str = "en-US-ChristopherNeural"
) -> list[Path]:
    """Generate all voiceovers sequentially in a single async session."""
    results = []
    for i, (text, path) in enumerate(zip(texts, output_paths)):
        result = await generate_voiceover_edge(text, path, voice)
        results.append(result)
        # Small delay between requests to avoid rate limiting
        await asyncio.sleep(1.5)
    return results


def generate_voiceover_elevenlabs(text: str, output_path: Path, voice_id: str = "pNInz6obpgDQGcFmaJgB") -> Path:
    """Generate voiceover using ElevenLabs API (premium quality)."""
    from elevenlabs import ElevenLabs

    api_key = os.environ.get("ELEVENLABS_API_KEY")
    if not api_key:
        raise ValueError("ELEVENLABS_API_KEY not set")

    client = ElevenLabs(api_key=api_key)
    audio_gen = client.text_to_speech.convert(
        voice_id=voice_id,
        text=text,
        model_id="eleven_multilingual_v2",
    )

    with open(output_path, "wb") as f:
        for chunk in audio_gen:
            f.write(chunk)

    return output_path


# ---------------------------------------------------------------------------
# Visual scene generation
# ---------------------------------------------------------------------------

def _load_font(name: str, size: int):
    """Try to load a TrueType font, fall back to default."""
    from PIL import ImageFont
    for path in [name, f"C:/Windows/Fonts/{name}"]:
        try:
            return ImageFont.truetype(path, size)
        except (OSError, IOError):
            continue
    return ImageFont.load_default()


def _draw_gradient(draw, width: int, height: int, color_top: tuple, color_bot: tuple):
    """Draw a vertical gradient background."""
    for y in range(height):
        ratio = y / height
        r = int(color_top[0] + (color_bot[0] - color_top[0]) * ratio)
        g = int(color_top[1] + (color_bot[1] - color_top[1]) * ratio)
        b = int(color_top[2] + (color_bot[2] - color_top[2]) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))


def _draw_text_with_shadow(draw, pos, text: str, font, fill, shadow_color=(0, 0, 0), offset: int = 3, **kwargs):
    """Draw text with a drop shadow for readability."""
    x, y = pos
    # Shadow
    draw.text((x + offset, y + offset), text, fill=shadow_color, font=font, **kwargs)
    # Main text
    draw.text((x, y), text, fill=fill, font=font, **kwargs)


def _draw_glow_circle(img, cx: int, cy: int, radius: int, color: tuple, alpha: int = 30):
    """Draw a soft glowing circle for visual interest."""
    from PIL import Image, ImageDraw
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    od = ImageDraw.Draw(overlay)
    for r in range(radius, 0, -4):
        a = int(alpha * (r / radius))
        od.ellipse(
            [cx - r, cy - r, cx + r, cy + r],
            fill=(*color, a),
        )
    # Composite onto RGB image
    rgba = img.convert("RGBA")
    rgba = Image.alpha_composite(rgba, overlay)
    return rgba.convert("RGB")


def create_text_slide(
    text: str,
    output_path: Path,
    scene_type: str = "body",
    title: str = "",
    subtitle: str = "",
    scene_index: int = 0,
    total_scenes: int = 1,
    width: int = 1080,
    height: int = 1920,
) -> Path:
    """Create a professional styled text slide image for a scene."""
    from PIL import Image, ImageDraw
    import random

    # Visual themes per scene type: gradient colors + accent + glow
    themes = {
        "hook": {
            "grad_top": (10, 5, 30),
            "grad_bot": (40, 15, 5),
            "accent": (255, 165, 0),
            "text": (255, 255, 255),
            "glow": (255, 120, 0),
        },
        "body": {
            "grad_top": (5, 10, 35),
            "grad_bot": (10, 25, 50),
            "accent": (80, 180, 255),
            "text": (240, 240, 240),
            "glow": (50, 130, 255),
        },
        "climax": {
            "grad_top": (35, 5, 5),
            "grad_bot": (50, 10, 25),
            "accent": (255, 60, 60),
            "text": (255, 255, 255),
            "glow": (255, 40, 40),
        },
        "cta": {
            "grad_top": (5, 30, 15),
            "grad_bot": (10, 45, 30),
            "accent": (80, 255, 120),
            "text": (255, 255, 255),
            "glow": (50, 200, 80),
        },
    }
    theme = themes.get(scene_type, themes["body"])

    img = Image.new("RGB", (width, height), (0, 0, 0))
    draw = ImageDraw.Draw(img)

    # 1. Gradient background
    _draw_gradient(draw, width, height, theme["grad_top"], theme["grad_bot"])

    # 2. Glow effects for visual depth
    random.seed(hash(text) % 10000)  # Deterministic per scene
    for _ in range(3):
        gx = random.randint(100, width - 100)
        gy = random.randint(200, height - 200)
        gr = random.randint(200, 500)
        img = _draw_glow_circle(img, gx, gy, gr, theme["glow"], alpha=20)
    draw = ImageDraw.Draw(img)

    # 3. Accent bar at top
    draw.rectangle([(0, 0), (width, 6)], fill=theme["accent"])

    # Load fonts
    font_main = _load_font("arialbd.ttf", 56)     # Bold for main text
    font_title = _load_font("arial.ttf", 34)
    font_small = _load_font("arial.ttf", 28)
    font_sub = _load_font("arial.ttf", 32)
    font_label = _load_font("arialbd.ttf", 44)

    # 4. Scene counter top-right
    counter = f"{scene_index + 1}/{total_scenes}"
    draw.text((width - 60, 40), counter, fill=theme["accent"], font=font_small, anchor="rm")

    # 5. Title at top
    if title:
        title_wrapped = textwrap.fill(title, width=32)
        _draw_text_with_shadow(
            draw, (width // 2, 100), title_wrapped,
            fill=theme["accent"], font=font_title,
            anchor="mm", align="center", offset=2,
        )

    # 6. Scene type label (large, above center text)
    label = {
        "hook": "[ HOOK ]",
        "body": "[ BUILD ]",
        "climax": "[ REVEAL ]",
        "cta": "[ YOUR TURN ]",
    }.get(scene_type, "")
    if label:
        y_label = height // 2 - 280
        _draw_text_with_shadow(
            draw, (width // 2, y_label), label,
            fill=theme["accent"], font=font_label,
            anchor="mm", offset=2,
        )

    # 7. Decorative line under label
    line_y = height // 2 - 230
    line_w = 300
    draw.line(
        [(width // 2 - line_w // 2, line_y), (width // 2 + line_w // 2, line_y)],
        fill=theme["accent"], width=2,
    )

    # 8. Main text centered — large and bold
    wrapped = textwrap.fill(text, width=22)
    _draw_text_with_shadow(
        draw, (width // 2, height // 2 + 20), wrapped,
        fill=theme["text"], font=font_main,
        anchor="mm", align="center", offset=3,
    )

    # 9. Subtitle bar at bottom
    sub_text = subtitle or text
    sub_wrapped = textwrap.fill(sub_text, width=36)
    # Semi-transparent black bar
    bar_top = height - 180
    for y in range(bar_top, height):
        opacity = min(220, int(220 * (y - bar_top) / (height - bar_top)))
        draw.line([(0, y), (width, y)], fill=(0, 0, 0))
    # Subtitle text
    _draw_text_with_shadow(
        draw, (width // 2, height - 90), sub_wrapped,
        fill=(255, 255, 255), font=font_sub,
        anchor="mm", align="center", offset=2,
    )

    img.save(output_path, quality=95)
    return output_path


def generate_ai_image(prompt: str, output_path: Path) -> Path | None:
    """Generate an image using Gemini's image generation."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="gemini-2.0-flash-preview-image-generation",
            contents=f"Generate a photorealistic vertical image (9:16 aspect ratio) for a YouTube Short. Scene: {prompt}. Style: cinematic, dramatic lighting, construction/DIY aesthetic. No text in image.",
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"],
            ),
        )

        # Extract image from response
        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                with open(output_path, "wb") as f:
                    f.write(part.inline_data.data)
                return output_path

    except Exception as e:
        print(f"    AI image generation failed ({e.__class__.__name__}), using text slide fallback")

    return None


def generate_scene_image(
    scene: dict,
    output_path: Path,
    title: str = "",
    use_ai_images: bool = False,
    scene_index: int = 0,
    total_scenes: int = 1,
) -> Path:
    """Generate a visual for a scene — AI image if enabled, otherwise styled text slide."""
    if use_ai_images:
        result = generate_ai_image(scene["visual_desc"], output_path)
        if result:
            return result

    # Fallback: styled text slide
    return create_text_slide(
        scene["voiceover"],
        output_path,
        scene_type=scene["type"],
        title=title,
        scene_index=scene_index,
        total_scenes=total_scenes,
    )


# ---------------------------------------------------------------------------
# Video assembly
# ---------------------------------------------------------------------------

def get_audio_duration(audio_path: Path) -> float:
    """Get duration of audio file in seconds."""
    import moviepy
    clip = moviepy.AudioFileClip(str(audio_path))
    duration = clip.duration
    clip.close()
    return duration


def assemble_video(
    scenes: list[dict],
    scene_images: list[Path],
    scene_audios: list[Path],
    output_path: Path,
    title: str = "",
) -> Path:
    """Assemble scene images and audio into a vertical video."""
    import moviepy

    clips = []

    for i, (scene, img_path, audio_path) in enumerate(zip(scenes, scene_images, scene_audios)):
        audio = moviepy.AudioFileClip(str(audio_path))
        duration = audio.duration

        # Static image clip with audio — fast and reliable
        img_clip = (
            moviepy.ImageClip(str(img_path))
            .with_duration(duration)
            .with_audio(audio)
        )
        clips.append(img_clip)

    # Concatenate all scene clips
    final = moviepy.concatenate_videoclips(clips, method="compose")

    # Ensure it's under 60 seconds for Shorts
    if final.duration > 60:
        final = final.subclipped(0, 60)

    final.write_videofile(
        str(output_path),
        fps=24,
        codec="libx264",
        audio_codec="aac",
        preset="medium",
        threads=4,
        logger=None,
    )

    # Clean up
    final.close()
    for clip in clips:
        clip.close()

    return output_path


# ---------------------------------------------------------------------------
# Main video creation pipeline
# ---------------------------------------------------------------------------

def create_video(
    video_data: dict,
    output_dir: Path,
    voice_engine: str = "edge",
    use_ai_images: bool = False,
    video_index: int = 1,
) -> Path | None:
    """Create a single YouTube Short video from parsed script data."""

    title = video_data["title"]
    scenes = video_data["scenes"]
    safe_title = re.sub(r'[<>:"/\\|?*]', '', title)[:60]

    print(f"\n  [{video_index}] Creating: {title}")

    # Create temp directory for assets
    work_dir = output_dir / f"temp_{video_index:02d}"
    work_dir.mkdir(parents=True, exist_ok=True)

    scene_images: list[Path] = []
    scene_audios: list[Path] = []

    try:
        # Generate all voiceovers
        print(f"      Generating voiceovers ({len(scenes)} scenes)...")
        audio_paths = []
        for i in range(len(scenes)):
            audio_paths.append(work_dir / f"scene_{i:02d}.mp3")

        if voice_engine == "edge":
            texts = [s["voiceover"] for s in scenes]
            asyncio.run(generate_all_voiceovers_edge(texts, audio_paths))
        else:
            for i, scene in enumerate(scenes):
                generate_voiceover_elevenlabs(scene["voiceover"], audio_paths[i])
        scene_audios = audio_paths

        # Generate all visuals
        print(f"      Generating visuals ({len(scenes)} scenes)...")
        for i, scene in enumerate(scenes):
            img_path = work_dir / f"scene_{i:02d}.png"
            generate_scene_image(
                scene, img_path, title=title, use_ai_images=use_ai_images,
                scene_index=i, total_scenes=len(scenes),
            )
            scene_images.append(img_path)

        # Assemble final video
        print(f"      Assembling video...")
        video_path = output_dir / f"{video_index:02d}_{safe_title}.mp4"
        assemble_video(scenes, scene_images, scene_audios, video_path, title=title)

        print(f"      [OK] Video saved: {video_path.name}")
        return video_path

    except Exception as e:
        print(f"      [FAIL] Failed: {e}")
        import traceback
        traceback.print_exc()
        return None

    finally:
        # Clean up temp files
        import shutil
        try:
            shutil.rmtree(work_dir)
        except Exception:
            pass


def run_video_creation(
    scripts_path: str,
    output_dir: str = "./shorts_videos",
    voice_engine: str = "edge",
    use_ai_images: bool = False,
    limit: int | None = None,
) -> None:
    """Main entry point — parse scripts, create videos."""

    scripts_file = Path(scripts_path)
    if not scripts_file.exists():
        print(f"ERROR: Scripts file not found: {scripts_path}")
        sys.exit(1)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("  YOUTUBE SHORTS VIDEO CREATOR")
    print("=" * 60)
    print(f"  Scripts:    {scripts_file}")
    print(f"  Output:     {out.resolve()}")
    print(f"  Voice:      {voice_engine}")
    print(f"  AI Images:  {'Yes' if use_ai_images else 'No (text slides)'}")
    if limit:
        print(f"  Limit:      {limit} videos")
    print("=" * 60)

    # Parse scripts
    scripts_text = scripts_file.read_text(encoding="utf-8")
    videos = parse_scripts(scripts_text)
    print(f"\n  Parsed {len(videos)} video scripts.")

    if not videos:
        print("  ERROR: No scripts found. Check the format of your scripts file.")
        sys.exit(1)

    if limit:
        videos = videos[:limit]
        print(f"  Limited to first {limit} videos.")

    # Create each video
    created = []
    failed = []

    for i, video_data in enumerate(videos, 1):
        result = create_video(
            video_data,
            output_dir=out,
            voice_engine=voice_engine,
            use_ai_images=use_ai_images,
            video_index=i,
        )
        if result:
            created.append(result)
        else:
            failed.append(video_data["title"])

    # Summary
    print("\n" + "=" * 60)
    print("  VIDEO CREATION COMPLETE")
    print("=" * 60)
    print(f"  Created:  {len(created)} videos")
    if failed:
        print(f"  Failed:   {len(failed)} videos")
    print(f"  Output:   {out.resolve()}")
    print(f"\n  Videos ready to upload:")
    for p in created:
        print(f"    > {p.name}")
    if failed:
        print(f"\n  Failed titles:")
        for t in failed:
            print(f"    X {t}")
    print("=" * 60)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="YouTube Shorts Video Creator — AI-powered video production",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            '  python create_shorts.py --scripts results/scripts.md\n'
            '  python create_shorts.py --scripts results/scripts.md --voice elevenlabs\n'
            '  python create_shorts.py --scripts results/scripts.md --ai-images --limit 3\n'
        ),
    )
    parser.add_argument(
        "--scripts", "-s", required=True,
        help="Path to the scripts markdown file from youtube_viral_titles.py",
    )
    parser.add_argument(
        "--output-dir", "-o", default="./shorts_videos",
        help="Directory for output video files (default: ./shorts_videos)",
    )
    parser.add_argument(
        "--voice", "-v", choices=["edge", "elevenlabs"], default="edge",
        help="Voice engine: 'edge' (free) or 'elevenlabs' (premium, needs API key)",
    )
    parser.add_argument(
        "--ai-images", action="store_true",
        help="Generate AI images for scenes using Gemini (needs GEMINI_API_KEY)",
    )
    parser.add_argument(
        "--limit", "-l", type=int, default=None,
        help="Only create the first N videos",
    )

    args = parser.parse_args()

    if args.voice == "elevenlabs" and not os.environ.get("ELEVENLABS_API_KEY"):
        print("ERROR: ELEVENLABS_API_KEY not set. Use --voice edge for free voiceover.")
        sys.exit(1)

    run_video_creation(
        scripts_path=args.scripts,
        output_dir=args.output_dir,
        voice_engine=args.voice,
        use_ai_images=args.ai_images,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
